export const BACK_BUTTON_ROUTES: { [key in string]: string } = {
  "/profile": "/obmennik",
  "/profile/request": "/profile",
  "/exchange/type": "/obmennik",
  "/exchange/input": "/exchange/type",
  "/exchange/details": "/exchange/input",
  "/exchange/result": "/obmennik",
  "/faq": "/obmennik",
  "/transfer-abroad/type": "/obmennik",
  "/transfer-abroad/input/fta": "/transfer-abroad/type",
  "/transfer-abroad/input/fta/requisites-and-license": "/transfer-abroad/input/fta",
  "/transfer-abroad/input/invoice": "/transfer-abroad/type",
  "/transfer-abroad/input/chinese-platforms": "/transfer-abroad/type",
  "/transfer-abroad/input/cards": "/transfer-abroad/type",
  "/transfer-abroad/result": "/obmennik",
};
